## 1. Integer Indexing

In Numpy, integer indexing refers to the use of integer arrays as indices to select elements from another array.


In [2]:
import numpy as np

# Create an array of 10 random integers between 0 and 9
a = np.random.randint(0, 10, size=10)
print(a)

# Create an array of indices that we want to select from the above array
indices = np.array([2, 4, 5])

# Use the indices array to select elements from the original array
b = a[indices]
print(b)


[4 5 4 5 4 7 7 5 8 2]
[4 4 7]


In [3]:
# Using multidimensional arrays
c = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]])

# Create an array of indices for the rows and columns that we want to select
rows = np.array([0, 1])
cols = np.array([1, 2])

# Use the indices array to select elements from the original array
d = c[rows, cols]
print(d)

 # When integers are used for indexing. Each element of first dimension is paired with the element of the second dimension. 
 # So the index of the elements in this case are (0,1),(1,2) and the corresponding elements are selected.


[2 6]


In [5]:
x = np.array([[0, 1, 2], 
              [3, 4, 5], 
              [6, 7, 8],
              [9, 10, 11]])

rows = np.array([[0, 0],
                 [3, 3]])

cols = np.array([[0, 2],
                 [0, 2]])

y = x[rows, cols]

# Here each element of first array is paired with the equivalent element of the second array.
# so the index of elements in this case are (0, 0), (0, 2), (3, 0), (3, 2) nd the corresponding elements are selected

print(y)

[[ 0  2]
 [ 9 11]]


## 2. Boolean Indexing

Boolean array indexing in Numpy is a way to filter elements of an array based on a boolean condition. It allows you to select elements from an array that meet a certain condition, without having to use a for loop or list comprehension.

In [8]:
a = np.array([1, 2, 3, 4, 5, 6])

# Create a boolean array that checks if elements are greater than 3
condition = a > 3 # Returns a numpy array object

print(condition, type(condition))

# Use the boolean array as an index to select only the elements that meet the condition
b = a[condition]

print(b)


[False False False  True  True  True] <class 'numpy.ndarray'>
[4 5 6]


In [9]:
c = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

condition = c > 3
print(condition, type(condition))
print()

d = c[condition]
print(d)

[[False False False]
 [ True  True  True]
 [ True  True  True]] <class 'numpy.ndarray'>

[4 5 6 7 8 9]


In [10]:
# Applying multiple condition using NumPy conditional operators
condition1 = c > 3
condition2 = c < 8

d = c[condition1 & condition2]
print(d)

[4 5 6 7]


In [11]:
# Filtering NaN using bolean indexing
a = np.array([np.nan, 1, 2, np.nan, 3, 4, 5])
print(a)
print()

condition = ~ np.isnan(a)

print(a[condition])

[nan  1.  2. nan  3.  4.  5.]

[1. 2. 3. 4. 5.]
