In [ ]:
import numpy as np

In [ ]:
x = np.array([1,3,5,7,9]) # Create an array in Numpy
print(x)

[1 3 5 7 9]


In [ ]:
print(type(x))

<class 'numpy.ndarray'>


In [ ]:
l = []
for i in range(1, 6):
    val = int(input("Enter value: "))
    l.append(val)

print(np.array(l))

Enter value: 12
Enter value: 3
Enter value: 10
Enter value: 0
Enter value: 5
[12  3 10  0  5]


In [ ]:
print("Dimension of the array is",x.ndim) # Prints the dimension of the array

Dimension of the array is 1


In [ ]:
y = np.array([[2,4,6,8],[1,3,5,7]]) # 2D array
print("Array:\n",y)
print("Dimension:",y.ndim)

Array:
 [[2 4 6 8]
 [1 3 5 7]]
Dimension: 2


In [ ]:
y = np.array([[[2,4,6,8],[1,3,5,7],[7,9,6,0]]]) # 3D array
print("Array:\n",y)
print("Dimension:",y.ndim)

Array:
 [[[2 4 6 8]
  [1 3 5 7]
  [7 9 6 0]]]
Dimension: 3


In [ ]:
y = np.array([2,4,6,8], ndmin = 7) # Create a 7D array
print("Array:\n",y)
print("Dimension:",y.ndim)

Array:
 [[[[[[[2 4 6 8]]]]]]]
Dimension: 7


In [ ]:
y = np.array([[2,4,6,8],[1,3,5,7]], ndmin = 7) # Create a 7D array
print("Array:\n",y)
print("Dimension:",y.ndim)

Array:
 [[[[[[[2 4 6 8]
      [1 3 5 7]]]]]]]
Dimension: 7


In [6]:
# The numpy.asarray() method
# This function is used to create an array by using the existing data in the form of lists, or tuples. 
# This function is useful in the scenario where we need to convert a python sequence into the numpy array object.

# Syntax: numpy.asarray(arr, [dtype], [order])

In [7]:
# List to array
import numpy as np
my_list = [1, 3, 5, 7, 9]
  
print ("Input  list : ", my_list)
   
    
out_arr = np.asarray(my_list)
print ("output array from input list : ", out_arr) 

Input  list :  [1, 3, 5, 7, 9]
output array from input list :  [1 3 5 7 9]


In [10]:
# Tuple to array

my_tuple = ([1, 3, 9], [8, 2, 6])
   
print ("Input  tuple : ", my_tuple)
    
out_arr = np.asarray(my_tuple) 
print(out_arr)

Input  tuple :  ([1, 3, 9], [8, 2, 6])
[[1 3 9]
 [8 2 6]]
