##numpy.delete() method

Return a new array with sub-arrays along an axis deleted. For a one dimensional array, this returns those entries not returned by arr[obj].

    Syntax: numpy.delete(arr, obj, [axis])

    arr = Input array.

    obj = slice, int or array of ints; Indicate indices of sub-arrays to remove along the specified axis.

    axis = The axis along which to delete the subarray defined by obj. If axis is None, obj is applied to the flattened array.



In [1]:
import numpy as np

arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(arr)
print()

# Deletes row 1
np.delete(arr, 1, 0)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]



array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [2]:
# No axis is mentioned so it applies to an flattened input array. 
# Elements of index 1, 3 and 5 are deleted
np.delete(arr, [1,3,5])

array([ 1,  3,  5,  7,  8,  9, 10, 11, 12])

In [3]:
arr = np.array([1,2,3,4,5,6,7])
np.delete(arr, [1,4])

array([1, 3, 4, 6, 7])

In [ ]:
##

In [7]:
v = np.matrix([[1,2,3],[2,3,4]])
w = np.matrix([[1,2],[2,3],[4,5]])
print(v)
print()
print(w)
print()
print(v*w)
print()
print(v.dot(w))

[[1 2 3]
 [2 3 4]]

[[1 2]
 [2 3]
 [4 5]]

[[17 23]
 [24 33]]

[[17 23]
 [24 33]]
