## 1. numpy.insert() method

Insert values along the given axis before the given indices.

    Syntax: numpy.insert(arr, obj, values, [axis])

    arr = Input array.

    obj = int, slice or sequence of ints; Object that defines the index or indices before which values is inserted.

    values = array_like; Values to insert into arr. If the type of values is different from that of arr, values is converted to 
    the type of arr.values should be shaped so that arr[...,obj,...] = values is legal.

    axis = Axis along which to insert values. If axis is None then arr is flattened first.



In [18]:
import numpy as np
a = np.array([[1, 1], [2, 2], [3, 3]])
print(a)
print()

# No axis is given so input array is flatten before inserting
x = np.insert(a, 1, [1,2,3])
print(x)

[[1 1]
 [2 2]
 [3 3]]

[1 1 2 3 1 2 2 3 3]


In [8]:
# 5 goes to index 2 and 6 goes to index 5
np.insert(a, [2, 5], [5, 6])

array([1, 1, 5, 2, 2, 3, 6, 3])

In [20]:
# Inserting along axis 1
np.insert(a, 1, [1, 2, 3], axis=1)

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [22]:
# Inserting along axis 0
np.insert(a, 1, [1, 2], axis=0)

array([[1, 1],
       [1, 2],
       [2, 2],
       [3, 3]])

## 2. numpy.append() method

Append values to the end of an array.

    Syntax: numpy.append(arr, values, [axis])

    arr = Values are appended to a copy of this array.

    values = These values are appended to a copy of arr. 
    It must be of the correct dimension (the same dimension as arr). 
    If axis is not specified, values can be any shape and will be flattened before use.

    axis = The axis along which values are appended. If axis is not given, both arr and values are flattened before use.

In [23]:
np.append([1, 2, 3], [[4, 5, 6], [7, 8, 9]])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.append([[1, 2, 3], [4, 5, 6]], [[7, 8, 9]], axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
# But this gives error as the input array is not of same dimension as of the array to be appended
# np.append([[1, 2, 3], [4, 5, 6]], [7, 8, 9], axis=0)