## 1. The concatenate() method

Join a sequence of arrays along an existing axis.

    Syntax: numpy.concatenate((a1, a2, ...), [axis], [out], [dtype], [casting])

    a1, a2,... = sequence of array_like in the form of tuples/lists; The arrays must have the same shape, except in the dimension corresponding to axis (the first, by default).

    axis = The axis along which the arrays will be joined. If axis is None, arrays are flattened before use. Default is 0.

    out = ndarray; If provided, the destination to place the result. The shape must be correct, matching that of what concatenate would have returned if no out argument were specified.

    dtype = If provided, the destination array will have this dtype. Cannot be provided together with out.

    casting = {‘no’, ‘equiv’, ‘safe’, ‘same_kind’, ‘unsafe’}; Controls what kind of data casting may occur. Defaults to ‘same_kind’.

In [2]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

# Concatenating along axis 0
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [4]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 2]])

# Concatenating along axis 1
np.concatenate((a, b), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 2]])

In [7]:
# Since no axis is None, input arrays are flattened before concatenating
np.concatenate((a, b), axis = None)

array([1, 2, 3, 4, 5, 6, 7, 2])

## 2. The stack() method

stack() is used for joining multiple NumPy arrays. Unlike, concatenate(), it joins arrays along a new axis. It returns a NumPy array. To join 2 arrays, they must have the same shape and dimensions. (e.g. both (2,3)–> 2 rows,3 columns)

    Syntax: numpy.stack(arrays, [axis], [out], [dtype], [casting])


    arrays = sequence of array_like in the form of tupls/lists; Each array must have the same shape.

    axis = The axis in the result array along which the input arrays are stacked.

    out = ndarray; If provided, the destination to place the result. The shape must be correct, matching that of what stack would have returned if no out argument were specified.

    dtype = If provided, the destination array will have this dtype. Cannot be provided together with out.

    casting = {‘no’, ‘equiv’, ‘safe’, ‘same_kind’, ‘unsafe’}; Controls what kind of data casting may occur. Defaults to ‘same_kind’.

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Stacking 2 1D arrays along axis 0
c = np.stack([a, b], axis=0)

print(c)

[[1 2 3]
 [4 5 6]]


In [ ]:
# Stacking 2 1D arrays along axis 1
c = np.stack([a, b], axis=1)
print(c)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
x = np.array([[1, 2, 3],
              [4, 5, 6]])
 
y = np.array([[ 7,  8,  9],
              [10, 11, 12]])

# Stacking 2 2D arrays along axis 1
c = np.stack([x, y], axis=1)
print(c)

[[[ 1  2  3]
  [ 7  8  9]]

 [[ 4  5  6]
  [10 11 12]]]


In [ ]:
# Stacking 2 2D arrays along axis 0
c = np.stack([x, y], axis=0)
print(c)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


*The difference between concatenate() and stack() is that stack joins the along a new axis. Whereas concatenate() joins the array along an existing axis*

In [10]:
# EXAMPLE :: 

import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 2]])
x = np.concatenate((a, b), axis=0)
y = np.stack((a, b), axis=0)

print(x)
print()
print(y)

[[1 2]
 [3 4]
 [5 6]
 [7 2]]

[[[1 2]
  [3 4]]

 [[5 6]
  [7 2]]]
