# **Random Valued Arrays**

In [ ]:
import numpy as np

### **1. rand() method**

***Syntax*: random.rand([d0], [d1], ..., [dn])**

*Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).*

d0, d1,..., dn = The dimensions of the returned array, must be non-negative. If no argument is given a single Python float is returned.

In [5]:
# Returns a 3x2 matrix containing random values b/w [0, 1)
var = np.random.rand(3,2)
print(var)

[[0.7061056  0.41152253]
 [0.02812874 0.75074039]
 [0.38022969 0.04352858]]


In [13]:
# Returns a random float b/w [0, 1) since no argument is proveided
var = np.random.rand()
print(var)

0.24497201271400793


### **2. randn() method**

***Syntax*: random.randn([d0], [d1], ..., [dn])**

*Return a sample (or samples) from the “standard normal” distribution. This may return positive or negative values as well.*
*If positive int_like arguments are provided, randn generates an array of shape (d0, d1, ..., dn), filled with random floats sampled from a univariate “normal” (Gaussian) distribution of mean 0 and variance 1. A single float randomly sampled from the distribution is returned if no argument is provided.*


d0, d1,..., dn = The dimensions of the returned array, must be non-negative. If no argument is given a single Python float is returned.

In [12]:
# Returns a 3x2 matrix containing random values
var = np.random.randn(3,2)
print(var)

[[-1.53950503  1.51328982]
 [-0.57987375 -1.36096669]
 [ 0.21560775  0.33906582]]


In [18]:
# Returns a random float since no argument is proveided
var = np.random.randn()
print(var)

-1.710545529267457


### **3. randint() method**

***Syntax*: random.randint(low, [high], [size], [dtype])**

*Return random integers from low (inclusive) to high (exclusive).*

low = Lowest (signed) integers to be drawn from the distribution

high = If provided, one above the largest (signed) integer to be drawn from the distribution. If array-like, must contain integer values

size = Output array dimension (in form of a tuple or array). If the given shape is, e.g., (m, n, k), then m * n * k samples are drawn. Default is None, in which case a single value is returned.

dtype = Desired data type of the result. The default value is int.

In [26]:
# An 1D array of size 10 containing random integers between [3, 7)
var = np.random.randint(3, 7, size = [10])
print(var)

[6 5 5 3 3 3 3 5 3 4]


In [27]:
# An array of dimension 3 x 4 containing random integers between [3, 7)
var = np.random.randint(3, 7, size = [3, 4])
print(var)

[[5 6 6 6]
 [6 3 4 3]
 [4 4 5 3]]


In [28]:
# Generate a 1 x 3 array with 3 different upper bounds
var = np.random.randint(1, [3, 5, 10])
print(var)

[1 3 9]


In [29]:
# Generate a 1 x 3 array with 3 different lower bounds
var = np.random.randint([1, 5, 7], 10)
print(var)

[4 9 9]


In [31]:
# Generate a 2 x 3 array with corresponding lower and upper bounds
var = np.random.randint([1, 5, 7], [4, 8, 9], size = (2, 3))
print(var)

[[1 6 8]
 [1 6 7]]


### **4. choice() method**

***Syntax*: random.choice(a, [size], [replace], [p])**

*Generates a random sample from a given 1-D array*

a = 1-D array-like or int; If an ndarray, a random sample is generated from its elements. If an int, the random sample is generated as if it were np.arange(a)

size = Output array dimension (in form of a tuple or array). If the given shape is, e.g., (m, n, k), then m * n * k samples are drawn. Default is None, in which case a single value is returned.

replace = Whether the sample is with or without replacement. Default is True, meaning that a value of a can be selected multiple times.

p = 1-D array-like; The probabilities associated with each entry in a. If not given, the sample assumes a uniform distribution over all entries in a.

In [32]:
# Generate a uniform random sample from np.arange(5) of size 3
var = np.random.choice(5, 3)
print(var)

[0 2 1]


In [33]:
# Generate a non-uniform random sample from np.arange(5) of size 3
var = np.random.choice(5, 3, p=[0.1, 0, 0.3, 0.6, 0])
print(var)

[2 3 0]


In [34]:
# Generate a uniform random sample from np.arange(5) of size 3 without replacement
var = np.random.choice(5, 3, replace=False)
print(var)

[0 4 1]


In [36]:
arr = ['pooh', 'rabbit', 'piglet', 'Christopher']

# Generate a non-uniform random sample of 5 from the given 1D array
var = np.random.choice(arr, 5, p=[0.5, 0.1, 0.1, 0.3])
print(var)

['pooh' 'pooh' 'pooh' 'pooh' 'Christopher']
