##1. Reshaping to differnet dimensions

***Syntax*: numpy.reshape(a, newshape, [order]) or array_name.reshape(newshape, [order])**

a = array like; Array to be reshaped.

newshape = int or tuple of ints; The new shape should be compatible with the original shape. If an integer, then the result will be a 1-D array of that length. One shape dimension can be -1. In this case, the value is inferred from the length of the array and remaining dimensions.

order = Read the elements of a using this index order, and place the elements into the reshaped array using this index order. ‘C’ means to read / write the elements using C-like index order, with the last axis index changing fastest, back to the first axis index changing slowest. ‘F’ means to read / write the elements using Fortran-like index order, with the first index changing fastest, and the last index changing slowest. Default C.

In [1]:
import numpy as np
 
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])

# Reshaping 1 X 16 array into 4 x 4
new = np.reshape(arr, (4, 4))

print(new)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [2]:
arr = np.array([[1, 2, 3],
                 [4, 5, 6]])

# Reshaping 2 x 3 array into 3 X 2
new = np.reshape(arr, (3, 2))

print(new)

[[1 2]
 [3 4]
 [5 6]]


## 2. Transposing Arrays

Transposing arrays in NumPy ca be done in two ways:


*   Using  Numpy ndarray.T object.
*   Using numpy.transpose() method.



In [4]:
import numpy as np

arr = np.array([[1, 2, 3],
				[4, 5, 6],
				[7, 8, 9]])

# Before transpose
print(arr)
print()

# Using ndarray.T object
print(arr.T)
print()

# Using the numpy.transpose method
print(np.transpose(arr))


[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]
