Arrays can be split into multiple sub arrays using the numpy.split(), numpy.dsplit(), numpy.hsplit(), numpy.vsplit() functions

## 1. split() method

Split an array into multiple sub-arrays as views into ary.

    Syntax: numpy.split(ary, indices_or_sections, [axis])

    ary = Array to be divided into sub-arrays.

    indices_or_sections = If indices_or_sections is an integer, N, the array will be divided into N equal arrays along axis. 
    If such a split is not possible, an error is raised. 
    If indices_or_sections is a 1-D array of sorted integers, the entries indicate where along axis the array is split. 
    If an index exceeds the dimension of the array along axis, an empty sub-array is returned correspondingly.

    axis = The axis along which to split, default is 0.

In [1]:
import numpy as np

x = np.arange(9)

# Splitting the arrays into 3 sub arrays
a = np.split(x, 3)

print(a)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


In [4]:
x = np.arange(8)
print(x)
print()

# As section is an 1D array so breaking the array into [0:3], [3:5], [5:6], [6:10]
a = np.split(x, [3, 5, 6, 10])
print(a)

[0 1 2 3 4 5 6 7]

[array([0, 1, 2]), array([3, 4]), array([5]), array([6, 7]), array([], dtype=int64)]


## 2. dsplit() method

Split array into multiple sub-arrays along the 3rd axis (depth).
dsplit only works on arrays of 3 or more dimensions.

    Syntax: numpy.dsplit(ary, indices_or_sections)

In [5]:
x = np.arange(16.0).reshape(2, 2, 4)
print(x)
print()

a = np.dsplit(x, 2)
print(a)

[[[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]]

 [[ 8.  9. 10. 11.]
  [12. 13. 14. 15.]]]

[array([[[ 0.,  1.],
        [ 4.,  5.]],

       [[ 8.,  9.],
        [12., 13.]]]), array([[[ 2.,  3.],
        [ 6.,  7.]],

       [[10., 11.],
        [14., 15.]]])]


## 3. hsplit() method

Split an array into multiple sub-arrays horizontally (column-wise).

    Syntax: numpy.dsplit(ary, indices_or_sections)

In [11]:
x = np.arange(16.0).reshape(4, 4)
print(x)
print()

a = np.hsplit(x, 2)
print(a)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]

[array([[ 0.,  1.],
       [ 4.,  5.],
       [ 8.,  9.],
       [12., 13.]]), array([[ 2.,  3.],
       [ 6.,  7.],
       [10., 11.],
       [14., 15.]])]


In [12]:
# As section is an 1D array so breaking the array col wise into [0:3], [3:6]
a = np.hsplit(x, np.array([3, 6]))
print(a)

[array([[ 0.,  1.,  2.],
       [ 4.,  5.,  6.],
       [ 8.,  9., 10.],
       [12., 13., 14.]]), array([[ 3.],
       [ 7.],
       [11.],
       [15.]]), array([], shape=(4, 0), dtype=float64)]


In [15]:
x = np.array([0, 1, 2, 3, 4, 5])
print(x)
print()

a = np.hsplit(x, 2)
print(a)

[0 1 2 3 4 5]

[array([0, 1, 2]), array([3, 4, 5])]


## 4. vsplit() method

Split an array into multiple sub-arrays vertically (row-wise).

    Syntax: numpy.dsplit(ary, indices_or_sections)

In [13]:
x = np.arange(16.0).reshape(4, 4)
print(x)
print()

a = np.vsplit(x, 2)
print(a)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]

[array([[0., 1., 2., 3.],
       [4., 5., 6., 7.]]), array([[ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])]


In [14]:
# As section is an 1D array so breaking the array row wise into [0:3], [3:6]
a = np.vsplit(x, np.array([3, 6]))
print(a)

[array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]]), array([[12., 13., 14., 15.]]), array([], shape=(0, 4), dtype=float64)]
